- alias: avantika
  image: images/team/ava
  social:
    -
      website:
        img: images/social/web.svg
        link: https://iamavu.com/
      github:
        img: images/social/github.svg
        link: https://github.com/iamavu
      twitter:
        img: images/social/twitter.svg
        link: https://twitter.com/iamavu
      linkedin:
        img: images/social/linkedin.svg
        link: https://www.linkedin.com/in/iamavu/

- alias: Legend
  image: images/team/legend
  social:
    -
      website:
        img: images/social/disabled_web.svg
        link:
      github:
        img: images/social/disabled_github.svg
        link: 
      twitter:
        img: images/social/twitter.svg
        link: https://twitter.com/pwnlegend
      linkedin:
        img: images/social/disabled_linkedin.svg
        link:

- alias: nigamelastic
  image: images/team/nigam
  social:
    -
      website:
        img: images/social/web.svg
        link: https://kshitijnigam.com/
      github:
        img: images/social/github.svg
        link: https://github.com/nigamelastic
      twitter:
        img: images/social/twitter.svg
        link: https://twitter.com/nigamelastic
      linkedin:
        img: images/social/linkedin.svg
        link: https://www.linkedin.com/in/kshitijnigam

- alias: starry-lord
  image: images/contrib/starry_lord
  social:
    -
      website:
        img: images/social/web.svg
        link: https://starrylord.ch
      github:
        img: images/social/github.svg
        link: https://github.com/Starry-lord/
      twitter:
        img: images/social/disabled_twitter.svg
        link:
      linkedin:
        img: images/social/linkedin.svg
        link: https://www.linkedin.com/in/sami-chakrouns

- alias: thewhiteh4t
  image: images/team/twh
  social:
    -
      website:
        img: images/social/web.svg
        link: https://thewhiteh4t.github.io/
      github:
        img: images/social/github.svg
        link: https://github.com/
      twitter:
        img: images/social/twitter.svg
        link: https://twitter.com/thewhiteh4t
      linkedin:
        img: images/social/linkedin.svg
        link: https://www.linkedin.com/in/lohityapushkar